spring:
  config:
    activate:
      on-profile: prod
  logging:
    level:
      root: WARN
      org.technoready.meliecommerce: INFO
      org.technoready.meliecommerce.exception: WARN
    file:
      name: logs/meliecommerce-prod.log

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080