spring:
  application:
    name: Meli-E-commerce
  profiles:
    active: dev
logging:
  level:
    root: INFO
    org.technoready.meliecommerce: DEBUG
    org.technoready.meliecommerce.service: DEBUG
    org.technoready.meliecommerce.controller: DEBUG
    org.technoready.meliecommerce.exception: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/meliecommerce.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha